// Generated by cargo run -p xtask -- types. Do not edit.
export type RepositoryId = string;
export type SourceId = string;
export type SnapshotId = string;
export type ContextId = string;
export type FileId = string;
export type DefinitionId = string;
export type RelationId = string;
export type EvidenceId = string;
export type Status = "complete" | "partial" | "failed" | "unavailable";
export type UnknownReason = "missing_dependency" | "cfg_unknown" | "macro_unavailable" | "indirect_target_unknown" | "external_boundary" | "unsupported_construct" | "budget_exhausted" | "analysis_failed" | "artifact_mismatch" | "syntax_only";
export type ReasonCount = { reason: UnknownReason, count: number, };
export type Coverage = { status: Status, reasons: Array<ReasonCount>, limitations: Array<string>, };
export type SourceFile = { id: FileId, path: string, content_hash: string, text: string, };
export type SourceSnapshot = { id: SourceId, repository_id: RepositoryId, revision: string, files: Array<SourceFile>, manifests: { [key in string]?: string }, warnings: Array<string>, };
export type CrateInput = { name: string, root_file: string, edition: string, dependencies: { [key in string]?: string }, };
export type BuildContext = { id: ContextId, name: string, target: string, features: Array<string>, default_features: boolean, cfg: { [key in string]?: string | null }, crates: Array<CrateInput>, manifest_digest: string, trust: string, coverage: Coverage, };
export type Span = { file_id: FileId, start: number, end: number, };
export type CfgStatus = "active" | "inactive" | "unknown";
export type Metrics = { lines: number, branches: number, returns: number, awaits: number, unsafe_blocks: number, };
export type Definition = { id: DefinitionId, context_id: ContextId, file_id: FileId, name: string, qualified_name: string, kind: string, parent_id: DefinitionId | null, signature: string, signature_hash: string, body_hash: string, span: Span, body_span: Span | null, cfg: Array<string>, cfg_status: CfgStatus, visibility: string, metrics: Metrics, };
export type Target = { "kind": "resolved", id: DefinitionId, } | { "kind": "unknown", reason: UnknownReason, label: string, };
export type Relation = { id: RelationId, source: DefinitionId, target: Target, kind: string, span: Span, evidence_id: EvidenceId, };
export type Evidence = { id: EvidenceId, basis: string, producer: string, inputs: Array<string>, assumptions: Array<string>, limitations: Array<string>, };
export type Diagnostic = { path: string | null, severity: string, message: string, };
export type FlowPoint = { kind: string, label: string, span: Span, };
export type FunctionFlow = { definition_id: DefinitionId, phase: string, points: Array<FlowPoint>, coverage: Coverage, };
export type FactBatch = { schema_version: number, source: SourceSnapshot, context: BuildContext, producer: string, definitions: Array<Definition>, relations: Array<Relation>, evidence: Array<Evidence>, flows: Array<FunctionFlow>, coverage: Coverage, diagnostics: Array<Diagnostic>, };
export type Snapshot = { id: SnapshotId, source_id: SourceId, repository_id: RepositoryId, context: BuildContext, revision: string, created_at: string, file_count: number, definition_count: number, relation_count: number, coverage: Coverage, producer: string, fact_digest: string, };
export type Page = { truncated: boolean, next_cursor: string | null, };
export type Work = { deadline_reached: boolean, elapsed_ms: number, };
export type QueryResponse<T> = { api_version: string, snapshot_id: SnapshotId, context_id: ContextId, items: Array<T>, coverage: Coverage, page: Page, work: Work, };
export type Direction = "incoming" | "outgoing" | "both";
export type GraphRequest = { snapshot_id: SnapshotId, context_id: ContextId, definition_id: DefinitionId, direction: Direction, depth: number, max_nodes: number, max_edges: number, };
export type GraphResponse = { api_version: string, snapshot_id: SnapshotId, context_id: ContextId, nodes: Array<Definition>, edges: Array<Relation>, coverage: Coverage, page: Page, work: Work, };
export type SourceWindow = { snapshot_id: SnapshotId, file_id: FileId, path: string, content_hash: string, text: string, start_line: number, total_lines: number, start_byte: number, truncated: boolean, encoding: string, };
export type DefinitionDetail = { snapshot_id: SnapshotId, definition: Definition, evidence: Array<Evidence>, coverage: Coverage, };
export type DiffRequest = { before: SnapshotId, after: SnapshotId, };
export type DefinitionChange = { kind: string, before: Definition | null, after: Definition | null, correspondence: string, changed_fields: Array<string>, };
export type DiffResponse = { before: SnapshotId, after: SnapshotId, context_changed: boolean, changes: Array<DefinitionChange>, impact_candidates: Array<Definition>, coverage: Coverage, truncated: boolean, };
export type Capabilities = { api_version: string, schema_version: number, analysis_levels: Array<string>, graph_families: Array<string>, trust_modes: Array<string>, limitations: Array<string>, };
export type ApiError = { code: string, message: string, correlation_id: string, };
export type SnapshotPinRequest = { context_id: ContextId, name: string, };
export type SnapshotPinState = { snapshot_id: SnapshotId, context_id: ContextId, name: string, retained: boolean, };
export type SnapshotPreparation = { snapshot_id: SnapshotId, context_id: ContextId, ready: boolean, };
export type TestOutcome = "pass" | "fail" | "expected_fail" | "unexpected_pass" | "timeout" | "infrastructure_error" | "not_run" | "unknown";
export type ArtifactIdentity = { sha256: string, source_id: SourceId, context_id: ContextId, producer: string, };
export type TestObservation = { name: string, outcome: TestOutcome, elapsed_ns: string | null, timeout_ns: string | null, reason: string | null, definition_ids: Array<DefinitionId>, };
export type TraceEvent = { sequence: string, timestamp: string, kind: string, definition_id: DefinitionId | null, correlation_id: string | null, loss_count: string | null, };
export type TraceStream = { id: string, process_or_device: string, thread_or_hart: string, clock_domain: string, timestamp_unit: string, events: Array<TraceEvent>, };
export type ObservationBundle = { schema_version: number, snapshot_id: SnapshotId, artifact: ArtifactIdentity, tests: Array<TestObservation>, streams: Array<TraceStream>, limitations: Array<string>, };
export type ObservationSummary = { id: string, snapshot_id: SnapshotId, artifact: ArtifactIdentity, test_count: number, event_count: number, clock_domains: Array<string>, limitations: Array<string>, };
export type ObservationWindow = { summary: ObservationSummary, tests: Array<TestObservation>, streams: Array<TraceStream>, offset: number, next_offset: number | null, truncated: boolean, };
export type JobLevel = "syntax" | "semantic";
export type JobPriority = "foreground" | "workspace" | "background";
export type JobRequest = { profile: string, level: JobLevel, priority: JobPriority, context: BuildContext | null, };
export type JobStatus = "queued" | "running" | "cancelling" | "cancelled" | "succeeded" | "failed";
export type JobStage = "queued" | "capture" | "syntax" | "semantics" | "validation" | "publication" | "finished";
export type JobEvent = { sequence: number, timestamp_ms: string, stage: JobStage, status: JobStatus, };
export type JobRecord = { id: string, request: JobRequest, status: JobStatus, created_ms: string, snapshot_id: SnapshotId | null, message: string | null, events: Array<JobEvent>, };
export type AnalysisResponse<T> = { api_version: string, snapshot_id: SnapshotId, context_id: ContextId, analysis: T, };
export type PathRequest = { graph: GraphRequest, target: DefinitionId | null, };
export type TraceAlignmentRequest = { before_snapshot_id: SnapshotId, before_context_id: ContextId, before_observation_id: string, after_snapshot_id: SnapshotId, after_context_id: ContextId, after_observation_id: string, before_stream_id: string, after_stream_id: string, before_offset: number, after_offset: number, max_events: number, max_anchors: number, };
export type TraceAlignmentResponse<T> = { before: SnapshotId, after: SnapshotId, before_context: ContextId, after_context: ContextId, comparison: T, };
export type CompilerBundle = { schema_version: number, compiler: CompilerIdentity, inputs: CompilerInputs, phase: string, bodies: Array<CompilerBody>, limitations: Array<string>, };
export type CompilerIdentity = { adapter: string, adapter_version: string, release: string, commit_hash: string, commit_date: string, host: string, llvm_version: string, };
export type CompilerInputs = { manifest_hash: string, files: Array<CompilerSourceFile>, crate_name: string, crate_root: string, edition: string, target: string, panic_strategy: string, mir_opt_level: number, rustc_args: Array<string>, environment_policy: string, trust: string, compiled_artifact: CompilerArtifact | null, };
export type CompilerArtifact = { kind: string, sha256: string, };
export type CompilerSourceFile = { path: string, sha256: string, byte_length: number, };
export type CompilerSourceMapping = { "status": "exact", path: string, start_byte: number, end_byte: number, } | { "status": "unavailable", reason: string, };
export type CompilerBody = {
/**
 * Input-manifest-local identity, never a source DefinitionId.
 */
body_id: string, def_path: string, kind: string, span: CompilerSourceMapping, argument_count: number, locals: Array<CompilerLocal>, source_scopes: Array<CompilerSourceScope>, blocks: Array<CompilerBlock>, };
export type CompilerLocal = { index: number, role: string, names: Array<string>,
/**
 * Display-only compiler type spelling; consumers must not parse it.
 */
type_display: string, source_scope: number, span: CompilerSourceMapping, };
export type CompilerSourceScope = { index: number, parent: number | null, span: CompilerSourceMapping, inlined_def_path: string | null, };
export type CompilerBlock = { index: number, is_cleanup: boolean, statements: Array<CompilerStatement>, terminator: CompilerTerminator, };
export type CompilerStatement = { index: number, kind: string, source_scope: number, span: CompilerSourceMapping, locals: CompilerLocalEffects, };
export type CompilerLocalEffects = {
/**
 * Whole-local assignments only, not writes through aliases or projections.
 */
defs: Array<number>,
/**
 * Conservative local references, including address-taking and projections.
 */
uses: Array<number>, moves: Array<number>, storage_live: Array<number>, storage_dead: Array<number>, unknown_effects: Array<CompilerUnknownEffect>, };
export type CompilerUnknownEffect = "call" | "indirect_call" | "pointer_aliasing" | "borrow_aliasing" | "partial_write" | "drop" | "inline_assembly" | "intrinsic" | "retag" | "external_state";
export type CompilerTerminator = { kind: string, source_scope: number, span: CompilerSourceMapping, locals: CompilerLocalEffects,
/**
 * Call destinations become initialized only on the normal-return edge.
 */
normal_return_defs: Array<number>, successors: Array<CompilerSuccessor>, unwind: CompilerUnwind | null, call_target: CompilerCallTarget | null, assert_expected: boolean | null, };
export type CompilerSuccessor = { target: number, kind: CompilerEdgeKind,
/**
 * Unsigned MIR bit pattern, as decimal text to preserve all 128 bits.
 */
switch_value: string | null, };
export type CompilerEdgeKind = "normal" | "switch_value" | "otherwise" | "unwind" | "resume" | "coroutine_drop" | "imaginary";
export type CompilerUnwind = { "kind": "continue" } | { "kind": "unreachable" } | { "kind": "terminate", reason: string, } | { "kind": "cleanup", target: number, };
export type CompilerCallTarget = { "kind": "function_definition", def_path: string, is_local: boolean, } | { "kind": "indirect", reason: string, };
export type CompilerDefinitionMapping = { "status": "matched", definition_id: DefinitionId, } | { "status": "unmapped", reason: string, };
export type CompilerBodyMapping = { body_id: string, mapping: CompilerDefinitionMapping, };
export type CompilerImport = { snapshot_id: SnapshotId, context_id: ContextId, bundle: CompilerBundle, mappings: Array<CompilerBodyMapping>, coverage: Coverage, };
export type CompilerImportSummary = { id: string, snapshot_id: SnapshotId, context_id: ContextId, compiler: CompilerIdentity, phase: string, body_count: number, mapped_count: number, coverage: Coverage, };
export type CompilerFlowPage = { snapshot_id: SnapshotId, context_id: ContextId, import_id: string, definition_id: DefinitionId, compiler: CompilerIdentity, phase: string, input_manifest_hash: string, panic_strategy: string, body: CompilerBody, offset: number, total_blocks: number, next_offset: number | null, coverage: Coverage, };
export type AnalysisEnvelope = { algorithm_version: string, coverage: Coverage, truncated: boolean, cancelled: boolean, deadline_reached: boolean, assumptions: Array<string>, };
export type AnalysisLimits = { max_nodes: number, max_edges: number, max_visits: number, max_depth: number, max_response_bytes: number, };
export type UnknownFrontier = { source: DefinitionId, relation_id: RelationId, target_definition_id: DefinitionId | null, reason: UnknownReason, };
export type RecursiveComponent = { id: string, members: Array<DefinitionId>, recursive: boolean, };
export type ComponentLink = { source: string, target: string, };
export type DefinitionMetrics = { definition_id: DefinitionId, distinct_callers: number, distinct_callees: number, incoming_call_sites: number, outgoing_call_sites: number, unknown_call_sites: number, source_lines: number, source_branches: number, source_returns: number, source_awaits: number, source_unsafe_blocks: number, declared_public: boolean, };
export type MetricDistribution = { metric: string, minimum: number, median: number, p95: number, maximum: number, };
export type GraphAnalysis = { envelope: AnalysisEnvelope, selected_nodes: number, selected_call_sites: number, components: Array<RecursiveComponent>, component_links: Array<ComponentLink>, metrics: Array<DefinitionMetrics>, distributions: Array<MetricDistribution>, unknown_frontier: Array<UnknownFrontier>, };
export type PathOutcome = "found" | "not_found_in_selection" | "reachability_complete" | "unknown";
export type PathAnalysis = { envelope: AnalysisEnvelope, outcome: PathOutcome, path: Array<DefinitionId>, relations: Array<RelationId>, reachable: Array<DefinitionId>, unknown_frontier: Array<UnknownFrontier>, };
export type TraceCompareRequest = { before_stream_id: string, after_stream_id: string, before_offset: number, after_offset: number, max_events: number, max_anchors: number, };
export type TracePosition = { stream_id: string, sequence: string, timestamp: string, clock_domain: string, timestamp_unit: string, };
export type TraceDivergence = { reason: string, before: TracePosition | null, after: TracePosition | null, before_kind: string | null, after_kind: string | null, };
export type TraceComparison = { envelope: AnalysisEnvelope, before_artifact: ArtifactIdentity, after_artifact: ArtifactIdentity, anchor: string | null, compared_events: number, matching_prefix_events: number, ambiguous_anchors: Array<string>, first_observed_divergence: TraceDivergence | null, before_loss_count: string, after_loss_count: string, before_interval: string | null, after_interval: string | null, before_clock_domain: string, after_clock_domain: string, before_timestamp_unit: string, after_timestamp_unit: string, };
