[package]
name = "atlas-server"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
atlas-model.workspace = true
atlas-store.workspace = true
atlas-query.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
[dev-dependencies]
tempfile.workspace = true
